[package]
name = "user/debuggerui"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React-roblox = "jsdotlua/react-roblox@17.2.1"
React = "jsdotlua/react@17.2.1"
Otter = "jsdotlua/otter@1.2.1"
Rodux = "roblox/rodux@3.0.0"
Cryo = "ya-ya-620/cryo@1.1.0"